program main
    use acstem, only: GET_SIMULATED_IMAGE, SIMULATED_IMAGE
    USE ACSTEM_PARAMETERS, ONLY: LATTICE_CONSTANT, ATOMIC_NUM, NATOMS, &
        num_image_rows, num_image_cols, LOWERBOUND, UPPERBOUND, ATOMIC_RADIUS

        implicit none

!    INTEGER, PARAMETER :: NATOMS = 55, NROWS = 128, NCOLS=128, ATOMIC_NUM=79
    REAL(8), PARAMETER :: SIGMA = 1.0D0, BETA=0.0D0
!    REAL(8), PARAMETER, DIMENSION(2) :: XBOUND=(/-20.0D0, 20.0D0/)
!    REAL(8), PARAMETER, DIMENSION(2) :: YBOUND=XBOUND
    REAL(8), DIMENSION(NATOMS, NATOMS) :: DISTMAT
!    REAL(8), DIMENSION(NROWS, NCOLS) :: SIMULATED_IMAGE
    REAL(8), DIMENSION(3*NATOMS) :: COORDS
    CHARACTER(LEN=2) :: SYMBOL
    CHARACTER(LEN=50) :: FILENAME1 = "Sc_Au55", FILENAME
    INTEGER :: I, J,MYUNIT
    REAL(KIND=8), DIMENSION(2), PARAMETER :: XBOUND=(/LOWERBOUND(1), UPPERBOUND(1)/)
    REAL(KIND=8), DIMENSION(2), PARAMETER :: YBOUND=(/LOWERBOUND(2), UPPERBOUND(2)/)

    WRITE(FILENAME, "(A,A)") ADJUSTL(TRIM(FILENAME1)), ".xyz"
    OPEN(NEWUNIT=MYUNIT,FILE=ADJUSTL(TRIM(FILENAME)), ACTION="READ", STATUS="OLD")
    WRITE(FILENAME, "(A,A)") ADJUSTL(TRIM(FILENAME1)), "_out.xyz"
    OPEN(NEWUNIT=J, FILE=ADJUSTL(TRIM(FILENAME)))
    READ(MYUNIT, *)
    READ(MYUNIT, *)
    WRITE(J, *) NATOMS
    WRITE(J,*)
    DO I=1, NATOMS
        READ(MYUNIT, *) COORDS(3*I-2:3*I)
        PRINT*, "X, Y, Z = ", COORDS(3*I-2:3*I)
        !write(j, *)"Au ", 2.0D0*ATOMIC_RADIUS*COORDS(3*I-2:3*I)
        write(j, *)"Au ", Lattice_constant*COORDS(3*I-2:3*I)
        !write(j, *)"Au ", 0.52918D0*COORDS(3*I-2:3*I)
    ENDDO
    CLOSE(MYUNIT)
    close(j)
    COORDS = COORDS*LATTICE_CONSTANT
    CALL GET_SIMULATED_IMAGE(NATOMS, ATOMIC_NUM, num_image_rows, num_image_cols, COORDS, SIGMA, BETA, &
        XBOUND, YBOUND)
    OPEN(NEWUNIT=MYUNIT, FILE="sim_im55.txt", ACTION="WRITE", STATUS="REPLACE")
    DO I=1, num_image_rows
        WRITE(MYUNIT, *) SIMULATED_IMAGE(I, :)
    ENDDO
    DO J=1, NATOMS
        DO I=1, NATOMS
            DISTMAT(I, J) = HUGE(1.0D0)
            IF(I/=J) THEN
                DISTMAT(I, J) = NORM2(COORDS(3*I-2:3*I) - COORDS(3*J-2:3*J))
            ENDIF
        ENDDO
    ENDDO
    PRINT*, "MINDIST = ", MINVAL(DISTMAT)
    PRINT*, "MAXDIST = ", MAXVAL(DISTMAT)
end program main
