MODULE TEST_IMAGES
    IMPLICIT NONE
CONTAINS
    SUBROUTINE GET_IMAGE(NROWS, NCOLS, FILENAME, IMAGE)
        IMPLICIT NONE
        INTEGER, INTENT(IN) :: NROWS, NCOLS
        CHARACTER(LEN=*), INTENT(IN) :: FILENAME
        REAL(8), INTENT(OUT), DIMENSION(NROWS, NCOLS) ::IMAGE
        INTEGER :: I, J, MYUNIT
        OPEN(NEWUNIT=MYUNIT, FILE=ADJUSTL(TRIM(FILENAME)), ACTION="READ", STATUS="OLD")
        DO I=1, NROWS
            READ(MYUNIT, *) IMAGE(I, :)
        ENDDO
    END SUBROUTINE GET_IMAGE
END MODULE TEST_IMAGES
